### ISSUE TITLE
Reset context on each test case

### ISSUE THREAD

**Issue by richard-lopes-ifood** [EduardoRFS/jest-with-context#1]
What do you think about reset the context whenever you call `withContext`? This way we would achieve a clean context on each test case.

**Comment by EduardoRFS** [comment]
@richard-lopes-ifood Hmmm I think that each `withContext` creates it's own context, isn't that enough? Maybe you want to recreate the context on each test specifically?

https://github.com/EduardoRFS/jest-with-context/blob/master/src/index.ts#L62

**Comment by richard-lopes-ifood** [comment]
> Maybe you want to recreate the context on each test specifically?

Precisely! I'm using your lib in the following way:

```javascript
// TestContext is a class where I add everything related to the tests.
const withContext = createContext(new TestContext());

describe('test', () => {
  withContext("a description here", ({ test }) => {
    test("should return the expected value", (context) => {
      context.callMethodA();
      context.callMethodB();
      context.callMethodC();
      context.expectOrangesToBeOranges();
    });
  });

  withContext("a description here", ({ test }) => {
    // on the second test case, context object is the same than previous test case.
    test("should return another the expected value", (context) => {
      context.callMethodB();
      context.callMethodC();
      context.expectApplesToBeApples();
    });
  });
});
```

**Comment by EduardoRFS** [comment]
@richard-lopes-ifood that would be a problem, as there is no way to us to copy it. But you can do a wrapper, and that should solve your problem.

```javascript
const withContext = (...args) => createContext(new TestContext())(...args);
```

**Comment by richard-lopes-ifood** [comment]
Got it. The ideia you gave me I think it's enough. Thanks! =)
